remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dark" 

title                    : "Mario Dagrada"
title_separator          : "-"
subtitle                 : "Personal Website"
name : "Mario Dagrada"
email: "mariodagrada24@gmail.com"
description: >- # this means to ignore newlines until "baseurl:"
  Mario Dagrada Personal Website
url : https://madagra.github.io
baseurl : "/"
twitter_username: mariolix89
github_username: madagra
search: "false"
tagline: "Mario Dagrada"

# Build settings
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Sass/SCSS
sass:
  # sass_dir: _sass
  style: compressed

# Outputting
# permalink: /:categories/:title/
#paginate: 5 # amount of posts to show
#paginate_path: /page:num/
timezone: Europe/Amsterdam

include:
  - _pages

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

exclude:
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - Gemfile
  - README

keep_files:
  - .git
  - .svn

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-remote-theme

author:
  name     : "Mario Dagrada"
  avatar   : "/assets/images/bio-photo.jpg"
  bio      : "Developer, engineering manager and science enthusiast"
  location : "Eindhoven, The Netherlands"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/madagra"      
    - label: "Linkedn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/mariodagrada"
    - label: "Medium"
      icon: "fab fa-fw fa-medium"
      url: "https://medium.com/@mariodagrada"
    - label: "Google Scholar"
      icon: "fab fa-fw fa-google"
      url: "https://scholar.google.com/citations?user=7hnOB34AAAAJ&hl=en"
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/MarioDagrada"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/madagra"      
    - label: "Linkedn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/mariodagrada"
    - label: "Medium"
      icon: "fab fa-fw fa-medium"
      url: "https://medium.com/@mariodagrada"      
    - label: "Google Scholar"
      icon: "fab fa-fw fa-google"
      url: "https://scholar.google.com/citations?user=7hnOB34AAAAJ&hl=en"      
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/MarioDagrada"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

