export type Project = { slug: string; title: string; year: number; category: string; summary: string; image: string; stack: string[]; body: string[]; link?: { href: string; label: string }; reference?: { href: string; label: string } };
export const projects: Project[] = [
  { slug: "security-events-investigation", title: "Security Events Investigation Framework", year: 2021, category: "Cybersecurity", summary: "An event-correlation framework that turns network signals into contextualised issues for investigation.", image: "/assets/images/security-events.jpg", stack: ["Network security", "Event correlation", "OT", "Risk analysis"], body: ["The framework correlates network events using network-specific context—such as device relationships, vulnerabilities, risk posture, aggregation, clustering, pattern matching, and event chaining—to move analysts from isolated alerts to an investigable security issue.", "It constituted the basic building block for the OT threat-investigation features of Forescout eyeInspect, helping operational technology teams investigate threats in industrial networks with the context needed to prioritise and act."], link: { href: "https://patents.google.com/patent/US20210203673A1/en", label: "Read the patent" } },
  { slug: "quality-screener", title: "Quality Screener", year: 2025, category: "Finance", summary: "A free quality-focused stock screener for building thoughtful portfolios.", image: "/assets/images/quality-screener.jpg", stack: ["Product development", "Financial data", "Portfolio research"], body: ["Quality Screener began as a hobby project used internally with friends to research companies and build stock portfolios around a consistent quality-focused process.", "It is now offered publicly for free. The focus is on making the research workflow useful and approachable first; monetisation may follow later."], link: { href: "https://qualityscreener.io/", label: "Visit Quality Screener" } },
  { slug: "turborvb", title: "TurboRVB", year: 2020, category: "HPC", summary: "Accurate quantum Monte Carlo simulations for molecules and materials, built for extreme performance.", image: "/assets/images/turborvb.jpg", stack: ["Fortran", "C++", "MPI & OpenMP", "CUDA"], body: ["TurboRVB is an open-source scientific software package for accurate simulations of molecules and materials from first principles.", "During my PhD, I contributed code for periodic materials alongside efficient parallelisation schemes for large-scale simulations."], link: { href: "https://github.com/sissaschool/turborvb", label: "View on GitHub" } },
  { slug: "qadence", title: "Qadence", year: 2023, category: "Quantum computing", summary: "A differentiable, native digital-analog interface for quantum programs with PyTorch.", image: "/assets/images/qadence.jpg", stack: ["Python", "PyTorch", "Automatic differentiation", "Quantum computing"], body: ["Qadence is a scientific software package for creating quantum programs with a simple interface, automatic differentiation, and native support for the digital-analog paradigm of quantum computing.", "I steered the project’s architecture and roadmap at PASQAL, helping deliver an open-source foundation for quantum machine learning on neutral-atom quantum computers.", "After I left, the company took a different strategic direction and Qadence is currently not maintained."], reference: { href: "https://arxiv.org/abs/1812.03637", label: "Read about the digital-analog paradigm" }, link: { href: "https://github.com/pasqal-io/qadence", label: "View on GitHub" } },
  { slug: "forecast", title: "Forecasting energy consumption", year: 2020, category: "Machine learning", summary: "Real-time energy-consumption forecasting for buildings and factories.", image: "/assets/images/forecast.jpg", stack: ["Python", "scikit-learn", "PyTorch"], body: ["This project applied time-series forecasting techniques to real-world loads in building facilities and factories.", "The solution compared methods from exponential smoothing to gradient boosting and recurrent neural networks, with attention to edge-device performance."], link: { href: "https://madagra.substack.com/p/ml-time-series-forecasting-the-right-way-cbf3678845ff", label: "Read the article" } },
  { slug: "qubec", title: "QUBEC", year: 2021, category: "Quantum computing", summary: "A cloud platform that made quantum-chemistry simulations accessible on public quantum hardware.", image: "/assets/images/qubec.jpg", stack: ["Python", "FastAPI", "Terraform", "AWS"], body: ["QUBEC made complex quantum-chemistry simulations accessible through publicly available quantum computers and familiar chemistry-modelling tools.", "I built the platform from its cloud and availability foundations to the quantum algorithms running under the hood.", "QUBEC gained a substantial initial user base before being incorporated into PASQAL’s broader algorithm offering. It was a product ahead of its time, especially given the state of quantum hardware then."], link: { href: "https://aws.amazon.com/blogs/quantum-computing/quantum-chemistry-with-qucos-qubec-on-amazon-braket/", label: "Read the AWS story" } },
];
export const featuredProjects = ["turborvb", "quality-screener", "qadence"].flatMap((slug) => projects.filter((project) => project.slug === slug));
export const getProject = (slug: string) => projects.find((project) => project.slug === slug);
