export type Project = { slug: string; title: string; category: string; summary: string; image: string; stack: string[]; body: string[]; link?: { href: string; label: string } };
export const projects: Project[] = [
  { slug: "turborvb", title: "TurboRVB", category: "HPC", summary: "Accurate quantum Monte Carlo simulations for molecules and materials, built for extreme performance.", image: "/assets/images/turborvb.jpg", stack: ["Fortran", "C++", "MPI & OpenMP", "CUDA"], body: ["TurboRVB is an open-source scientific software package for accurate simulations of molecules and materials from first principles.", "During my PhD, I contributed code for periodic materials alongside efficient parallelisation schemes for large-scale simulations."], link: { href: "https://github.com/sissaschool/turborvb", label: "View on GitHub" } },
  { slug: "qadence", title: "Qadence", category: "Quantum computing", summary: "A differentiable interface for building and executing digital-analog quantum programs with PyTorch.", image: "/assets/images/qadence.jpg", stack: ["Python", "PyTorch", "Automatic differentiation", "Quantum computing"], body: ["Qadence is a scientific software package for creating quantum programs with a simple interface and automatic differentiation.", "I steered the project’s architecture and roadmap at PASQAL, helping deliver an open-source foundation for quantum machine learning."], link: { href: "https://github.com/pasqal-io/qadence", label: "View on GitHub" } },
  { slug: "forecast", title: "Forecasting energy consumption", category: "Machine learning", summary: "Real-time energy-consumption forecasting for buildings and factories.", image: "/assets/images/forecast.jpg", stack: ["Python", "scikit-learn", "PyTorch"], body: ["This project applied time-series forecasting techniques to real-world loads in building facilities and factories.", "The solution compared methods from exponential smoothing to gradient boosting and recurrent neural networks, with attention to edge-device performance."], link: { href: "https://medium.com/@MarioDagrada/ml-time-series-forecasting-the-right-way-cbf3678845ff", label: "Read the article" } },
  { slug: "qubec", title: "QUBEC", category: "Cloud & quantum", summary: "An AWS platform for performing quantum-chemistry simulations on quantum computers.", image: "/assets/images/qubec.jpg", stack: ["Python", "FastAPI", "Terraform", "AWS"], body: ["QUBEC made complex quantum-chemistry simulations accessible through publicly available quantum computers and familiar chemistry-modelling tools.", "I built the platform from its cloud and availability foundations to the quantum algorithms running under the hood."], link: { href: "https://aws.amazon.com/blogs/quantum-computing/quantum-chemistry-with-qucos-qubec-on-amazon-braket/", label: "Read the AWS story" } },
];
export const featuredProjects = projects;
export const getProject = (slug: string) => projects.find((project) => project.slug === slug);
