export const articles = [
  { year: "2024", title: "Sequences, Time Series and Prediction course in PyTorch", description: "Reworking the DeepLearning.ai course exercises from TensorFlow to PyTorch.", href: "https://madagra.substack.com/p/sequences-time-series-and-prediction-course-in-pytorch-167ba8591fe3" },
  { year: "2024", title: "Hands-on Introduction to Concurrency in Go", description: "Goroutines and channels explained by building a simple client-server chat.", href: "https://madagra.substack.com/p/hands-on-introduction-to-concurrency-in-go-ed2d5bf90112" },
  { year: "2023", title: "A system design journey", description: "Scaling a simple Go URL shortener into a distributed, highly available system on AWS.", href: "https://madagra.substack.com/p/a-system-design-journey-6cf85d6c6e0d" },
  { year: "2023", title: "A primer on functional PyTorch", description: "Writing Jax-style, functional PyTorch models with the functional API.", href: "https://madagra.substack.com/p/introduction-to-functional-pytorch-b5bf739e1e6e" },
  { year: "2022", title: "Introduction to Physics-informed Neural Networks", description: "A hands-on PyTorch tutorial on using neural networks to solve differential equations.", href: "https://madagra.substack.com/p/solving-differential-equations-with-neural-networks-afdcf7b8bcc4" },
  { year: "2021", title: "Database backup using AWS Lambda", description: "Automating a recurring database backup with a scheduled Lambda function.", href: "https://madagra.substack.com/p/database-backup-using-aws-lambda-d5d331591c40" },
  { year: "2021", title: "Private PyPI Server on AWS with Terraform", description: "Standing up a private Python package registry on AWS with infrastructure as code.", href: "https://madagra.substack.com/p/private-pypi-server-on-aws-with-terraform-1c6b9409b450" },
  { year: "2021", title: "Deploy a containerized application on AWS with Terraform", description: "A step-by-step guide to service-oriented deployment and infrastructure as code.", href: "https://madagra.substack.com/p/deploy-a-containerized-application-on-aws-with-terraform-bf929bb3bb6b" },
  { year: "2020", title: "Represent Hierarchical Data in Python", description: "Parsing and working with tree-structured JSON using the anytree library.", href: "https://madagra.substack.com/p/represent-hierarchical-data-in-python-cd36ada5c71a" },
  { year: "2020", title: "ML time series forecasting the right way", description: "An end-to-end guide to forecasting with machine learning, done properly.", href: "https://madagra.substack.com/p/ml-time-series-forecasting-the-right-way-cbf3678845ff" },
];


export const publications = [
  { year: "2024", title: "Qadence: a differentiable interface for digital-analog programs", authors: ["Dominik Seitz", "Niklas Heim", "João P. Moutinho", "Roland Guichard", "Vytautas Abramavicius", "Aleksander Wennersteen", "Gert-Jan Both", "Anton Quelle", "Caroline de Groot", "Gergana V. Velikova", "Vincent E. Elfving", "Mario Dagrada"], citation: "arXiv:2401.09915", href: "https://arxiv.org/abs/2401.09915" },
  { year: "2023", title: "Framework for investigating events", authors: ["Daniel Ricardo dos Santos", "Elisa Costante", "Mario Dagrada", "Alessandro Manzi"], citation: "US Patent 11,818,146", href: "https://patents.google.com/patent/US11818146B2/en" },
  { year: "2023", title: "Cloud on-demand emulation of quantum dynamics with tensor networks", authors: ["Kemal Bidzhiev", "Aleksander Wennersteen", "Mourad Beji", "Mario Dagrada", "Mauro D'Arcangelo", "Sebastian Grijalva", "Anne-Claire Le Henaff", "Anton Quelle", "Alvin Sashala Naik"], citation: "arXiv:2302.05253", href: "https://arxiv.org/abs/2302.05253" },
  { year: "2022", title: "Harmonic (Quantum) Neural Networks", authors: ["Atiyo Ghosh", "Antonio A. Gentile", "Mario Dagrada", "Chul Lee", "Seong-Hyok Kim", "Hyukgeun Cha", "Yunjun Choi", "Brad Kim", "Jeong-Il Kye", "Vincent E. Elfving"], citation: "arXiv:2212.07462", href: "https://arxiv.org/abs/2212.07462" },
  { year: "2021", title: "Leveraging Operational Technology and the Internet of Things to Attack Smart Buildings", authors: ["Daniel Ricardo dos Santos", "Mario Dagrada", "Elisa Costante"], citation: "arXiv:1912.02480", href: "https://arxiv.org/abs/1912.02480" },
  { year: "2020", title: "TurboRVB: a many-body toolkit for ab initio electronic simulations by quantum Monte Carlo", authors: ["Kousuke Nakano", "Claudio Attaccalite", "Matteo Barborini", "Luca Capriotti", "Michele Casula", "Emanuele Coccia", "Mario Dagrada", "Claudio Genovese", "Ye Luo", "Guglielmo Mazzola", "Andrea Zen", "Sandro Sorella"], citation: "arXiv:2002.07401", href: "https://arxiv.org/abs/2002.07401" },
  { year: "2019", title: "Efficient communication overlap by runtimes collaboration", authors: ["Marc Sergent", "Mario Dagrada", "Guillaume Papauré"], citation: "US Patent App. 16/215,633", href: "https://patents.google.com/patent/EP3502897A1/en" },
  { year: "2018", title: "Efficient communication/computation overlap with MPI+OpenMP runtimes collaboration", authors: ["Marc Sergent", "Mario Dagrada", "Patrick Carribault", "Julien Jaeger", "Marc Pérache", "Guillaume Papauré"], citation: "Euro-Par 2018", href: "https://doi.org/10.1007/978-3-319-96983-1_40" },
  { year: "2016", title: "Improved quantum Monte Carlo simulations: from open to extended systems", authors: ["Mario Dagrada"], citation: "PhD thesis", href: "https://tel.archives-ouvertes.fr/tel-01478313/document" },
  { year: "2016", title: "Exact special twist method for quantum Monte Carlo simulations", authors: ["Mario Dagrada", "Seher Karakuzu", "Verónica Laura Vildosola", "Michele Casula", "Sandro Sorella"], citation: "Physical Review B 94, 245108", href: "https://doi.org/10.1103/PhysRevB.94.245108" },
  { year: "2016", title: "Competing collinear magnetic structures in superconducting FeSe by first principles quantum Monte Carlo calculations", authors: ["Brian Busemeyer", "Mario Dagrada", "Sandro Sorella", "Michele Casula", "Lucas K. Wagner"], citation: "Physical Review B 94, 035108", href: "https://doi.org/10.1103/PhysRevB.94.035108" },
  { year: "2015", title: "Density Matrix Embedding scheme for optimal atomic basis set construction", authors: ["S. Sorella", "N. Devaux", "Mario Dagrada", "G. Mazzola", "M. Casula"], citation: "Journal of Chemical Physics 143, 244112", href: "https://doi.org/10.1063/1.4938089" },
  { year: "2014", title: "Quantum Monte Carlo study of the protonated water dimer", authors: ["Mario Dagrada", "Michele Casula", "Antonino M. Saitta", "Sandro Sorella", "Francesco Mauri"], citation: "Journal of Chemical Theory and Computation 10, 1980–1993", href: "https://doi.org/10.1021/ct401077x" },
  { year: "2012", title: "Entanglement-assisted calibration of a photon number resolving detector", authors: ["G. Brida", "L. Ciavarella", "Mario Dagrada", "I. P. Degiovanni", "M. Genovese", "A. Migdall", "M. G. Mingolla", "M. G. A. Paris", "F. Piacentini", "S. V. Polyakov"], citation: "QELS conference", href: "https://doi.org/10.1364/QELS.2012.QTu1E.4" },
];


export const selectedWriting = [
  { title: "Introduction to Physics-informed Neural Networks", description: "A practical introduction to using neural networks to solve differential equations by incorporating physical constraints.", href: "https://madagra.substack.com/p/solving-differential-equations-with-neural-networks-afdcf7b8bcc4" },
  { title: "Harmonic (Quantum) Neural Networks", description: "Research on quantum-inspired neural-network architectures built around harmonic structure and symmetry.", href: "https://arxiv.org/abs/2212.07462" },
  { title: "Efficient communication overlap by runtimes collaboration", description: "A patent covering runtime collaboration techniques that overlap communication and computation in parallel systems.", href: "https://patents.google.com/patent/EP3502897A1/en" },
  ...articles,
];
